// Set up required configuration to support the 11ty Bundle database utilities
export const config = {
  // Use the following for production
  // dbFilePath:
  //   "/Users/Bob/Dropbox/Docs/Sites/11tybundle.dev/src/_data/bundledb.json",
  // dbBackupDir:
  //   "/Users/Bob/Dropbox/Docs/Sites/11tybundle.dev/devdata/bundledb-backups",
  // badLinksDir: "/Users/Bob/Dropbox/Docs/Sites/11tybundle.dev/devdata/badlinks",

  // Use the following for testing
  dbFilePath: "/Users/Bob/Dropbox/Docs/Sites/dbtools/devdata/bundledb.json",
  dbBackupDir: "/Users/Bob/Dropbox/Docs/Sites/dbtools/devdata/bundledb-backups",
  badLinksDir: "/Users/Bob/Dropbox/Docs/Sites/dbtools/devdata/badlinks",
  categories: [
    "11ty Conference 2024",
    "Accessibility",
    "Asset Pipelines",
    "Blogging",
    "CMS",
    "CSS/Sass",
    "Collections",
    "Configuration",
    "Data Cascade",
    "Dates",
    "Debugging",
    "Deployment",
    "Drafts",
    "Edge Functions",
    "Filters",
    "From the Source",
    "Front Matter",
    "Getting Started",
    "Global Data",
    "How to...",
    "Images",
    "Internationalization",
    "Layouts",
    "Markdown",
    "Migrating to Eleventy",
    "Navigation",
    "Netlify",
    "Now Page",
    "Nunjucks/Macros",
    "Pagination",
    "Performance",
    "Plugins",
    "Permalinks",
    "Remote Data",
    "RSS",
    "Scheduling",
    "Search",
    "Serverless",
    "Shortcodes",
    "Social Media",
    "WebC",
    "Webmentions",
    "Why Eleventy?",
    "YouTube",
  ],
};
