// Set up required configuration to support the 11ty Bundle database utilities
export const config = {
  // Use the following for production
  dbFilePath:
    "/Users/Bob/Dropbox/Docs/Sites/11tybundle.dev/src/_data/bundledb.json",
  dbBackupDir:
    "/Users/Bob/Dropbox/Docs/Sites/11tybundle.dev/devdata/bundledb-backups",
  badLinksDir: "/Users/Bob/Dropbox/Docs/Sites/11tybundle.dev/devdata/badlinks",

  // Use the following for testing
  // dbFilePath: "/Users/Bob/Dropbox/Docs/Sites/dbtools/devdata/bundledb.json",
  // dbBackupDir: "/Users/Bob/Dropbox/Docs/Sites/dbtools/devdata/bundledb-backups",
  // badLinksDir: "/Users/Bob/Dropbox/Docs/Sites/dbtools/devdata/badlinks",
  // categories: [
  //   { value: "11ty Conference 2024" },
  //   { value: "Accessibility" },
  //   { value: "Asset Pipelines" },
  //   { value: "Blogging" },
  //   { value: "CMS" },
  //   { value: "CSS/Sass" },
  //   { value: "Collections" },
  //   { value: "Configuration" },
  //   { value: "Data Cascade" },
  //   { value: "Dates" },
  //   { value: "Debugging" },
  //   { value: "Deployment" },
  //   { value: "Drafts" },
  //   { value: "Edge Functions" },
  //   { value: "Filters" },
  //   { value: "From the Source" },
  //   { value: "Front Matter" },
  //   { value: "Getting Started" },
  //   { value: "Global Data" },
  //   { value: "How to..." },
  //   { value: "Images" },
  //   { value: "Image Galleries" },
  //   { value: "Internationalization" },
  //   { value: "Layouts" },
  //   { value: "Markdown" },
  //   { value: "Migrating to Eleventy" },
  //   { value: "Navigation" },
  //   { value: "Netlify" },
  //   { value: "Now Page" },
  //   { value: "Nunjucks/Macros" },
  //   { value: "Pagination" },
  //   { value: "Performance" },
  //   { value: "Plugins" },
  //   { value: "Permalinks" },
  //   { value: "Remote Data" },
  //   { value: "RSS" },
  //   { value: "Scheduling" },
  //   { value: "Search" },
  //   { value: "Serverless" },
  //   { value: "Shortcodes" },
  //   { value: "Social Media" },
  //   { value: "WebC" },
  //   { value: "Webmentions" },
  //   { value: "Why Eleventy?" },
  //   { value: "YouTube" },
  // ],
};
